config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post 'vote'
    end
  end

  namespace :admin do
    resources :candidates
  end

  root 'candidates#index'
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :votes
  validates :name, presence: true, length: {minimum: 2}
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :candidate, counter_cache: true
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only:[:vote, :edit, :update, :destroy]

  def index
    @candidates = Candidate.all
  end

  def vote
    Vote.create(candidate: @candidate)
    redirect_to :back, notice: '投票完成'
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to candidates_path, notice: "新增候選人成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candidate.update_attributes(candidate_params)
      redirect_to candidates_path, notice:'更新成功'
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path, notice:'已刪除'
  end

  private
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
    redirect_to candidates_path, notice: '找不到人' if not @candidate
  end

  def candidate_params
    params.require(:candidate).permit(:name)
  end
end

app/helpers/admin/candidates_helper.rb
module Admin::CandidatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/admin/candidates/index.html.erb
<h1>Welcome!</h1>

app/views/candidates/_form.html.erb
<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@candidate) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>更新候選人</h1>

<%= render 'form' %>

app/views/candidates/index.html.erb
<%= flash[:notice] %>
<h1>你好</h1>
<%= link_to '新增候選人', new_candidate_path %>

<ul>
  <% @candidates.each do |candidate| %>
    <li>
      <%= candidate.name %>
      <%= candidate.votes.size %>
      <%= link_to '投票', vote_candidate_path(candidate), method: :post, data:{confirm:'你確定嗎?'} %>
    </li>
  <% end %>
</ul>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyVote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>